### ISSUE TITLE
🚀 OctokitGitHubClient Implementation

### ISSUE THREAD

**Issue by Strypper** [Strypper/mauisland#183]
### Description

Implement logic that follows this interface 

```cs

namespace MAUIsland.GitHubProvider;

public interface IGitHubService
{
    Task<GitHubRepositoryModel> GetRepository(string owner, string repository);

    Task<GitHubAuthorModel> GetAuthor(string owner);

    Task<IEnumerable<GitHubIssueModel>> GetGitHubIssues(string owner, string repository);

    Task<IEnumerable<GitHubIssueModel>> GetGitHubIssuesByLabels(string owner, string repository, IEnumerable<string> labels);

    Task<GitHubIssueModel> GetGitHubIssueById(string owner, string repository, string issueNumber);
}

```

### Testing Your Implementation
To test your implementation:

1. Open GitHubServiceIntegrationTest.cs where all test cases are provided to interact with your logic.
2. Choose the test you want to execute.
3. Select "Debug Test".
4. Set breakpoints within your implementation methods to inspect the code flow and ensure correct behavior.

### Public API Changes
```cs

    Task<GitHubRepositoryModel> GetRepository(string owner, string repository);

    Task<GitHubAuthorModel> GetAuthor(string owner);

    Task<IEnumerable<GitHubIssueModel>> GetGitHubIssues(string owner, string repository);

    Task<IEnumerable<GitHubIssueModel>> GetGitHubIssuesByLabels(string owner, string repository, IEnumerable<string> labels);

    Task<GitHubIssueModel> GetGitHubIssueById(string owner, string repository, string issueNumber);
```

### Intended Use-Case
Get information:
1. GitHub repository
2. GitHub repository issues
3. GitHub Author

### Tasks

- [ ]     Task<GitHubRepositoryModel> GetRepository(string owner, string repository);
- [ ]     Task<GitHubAuthorModel> GetAuthor(string owner);
- [ ]     Task<IEnumerable<GitHubIssueModel>> GetGitHubIssues(string owner, string repository);
- [ ]     Task<IEnumerable<GitHubIssueModel>> GetGitHubIssuesByLabels(string owner, string repository, IEnumerable<string> labels);
- [ ]     Task<GitHubIssueModel> GetGitHubIssueById(string owner, string repository, string issueNumber);

**Comment by Strypper** [comment]
Implemented
